CREATE TABLE CUSTOMER
(
  ID bigint,
  SSN char(25),
  NAME varchar(64),
  CONSTRAINT CUSTOMER_PK PRIMARY KEY(ID)
);
INSERT INTO CUSTOMER (ID,SSN,NAME) VALUES (10, 'CST01002','Joseph Smith');
INSERT INTO CUSTOMER (ID,SSN,NAME) VALUES (11, 'CST01003','Nicholas Ferguson');
INSERT INTO CUSTOMER (ID,SSN,NAME) VALUES (12, 'CST01004','Jane Aire');
